version: '3.8'
services:
  web:
    build: 
      context: . 
      dockerfile: Dockerfile
    image: Project3_image
    container_name: Project3
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      PROJECT3_DEBUG: "1"